# Generated by Django 5.1.4 on 2025-02-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('start_date', models.DateField()),
                ('phase', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=512)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisModule.project')),
            ],
        ),
    ]
